#
# Auto Deploy to VPS
#

name: Build & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push with following branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            # DOWNLOAD AND INSTALL APP
            # cd /home/apps # go to app dir
            # rm -rf {REPO_NAME}/ # wipe out app for fresh build
            # git clone https://github.com/UnfocusedDrive/{REPO_NAME}.git # get latest
            # cd {REPO_NAME} # go to app dir
            # npm install # get latest packages
            # npm run build # build app

            # MOVE APP TO STAGING WWW
            # rm -rf /var/www/unstable.memoryleak.ai/{DIR_NAME}/ # remove dir
            # mkdir /var/www/unstable.memoryleak.ai/{DIR_NAME}/ # rebuild dir
            # sudo mv -i dist/* /var/www/unstable.memoryleak.ai/{DIR_NAME}/ # move build to serve dir
            # echo 'Successfully deployed to unstable.memoryleak.ai/{DIR_NAME}/'
